spring:
  application:
    name: mls-coordonnees-patient
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL} #jdbc:mysql://localhost:3306/mls?serverTimezone=UTC
    username: mls
    password: mls
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER} #http://localhost:8089/eureka