spring:
  application:
    name: front-mls
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mls-mysql:3306/mls?serverTimezone=UTC
    username: mls
    password: mls
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
server:
  port: 8080
