spring:
  application:
    name: mls-gateway
  cloud:
      gateway:
        mvc:
          routes:
          - id: coordonnees-patient
            uri: lb://mls-donnees-patient
            predicates:
              - Path=gateway/coordonneesPatient/all
            filters:
              - SetPath=/coordonneesPatient/all
  security:
    user:
      name: phildev
      password: mls2024@
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8089/eureka


