spring:
  application:
      name: mls-notes-patient
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URL}
      username: ${MONGO_USER}
      password: ${MONGO_PWD}
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER} #http://localhost:8089/eureka
