spring:
  application:
      name: mls-notes-patient
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URL}
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER} #http://localhost:8089/eureka

logging:
  level:
    root: error
    com.phildev.mls.notes.patient: debug
